import { ProductSchema } from "./product";
import { Types } from "mongoose";

const productSeeds = (owner: Types.ObjectId): ProductSchema[] => {
    return [
        {
            name: "infinity gauntlet",
            category: "accessories",
            price: 10,
            description: "infinity gauntlet for kids",
            image: `/img/1.png`,
            onSale: true,
            owner,
        },
        {
            name: "toy ms marvel",
            category: "accessories",
            price: 12,
            description: "toy ms marvel for kids",
            image: `/img/2.png`,
            onSale: true,
            owner,
        },
        {
            name: "toy flash",
            category: "accessories",
            price: 8,
            description: "toy flash for kid",
            image: `/img/3.png`,
            onSale: true,
            owner,
        },
        {
            name: "clothes marvel",
            category: "clothes",
            price: 18,
            description: "article of clothing",
            image: `/img/4.png`,
            onSale: true,
            owner,
        },
        {
            name: "infinity gauntlet",
            category: "accessories",
            price: 10,
            description: "infinity gauntlet for kids",
            image: `/img/1.png`,
            onSale: true,
            owner,
        },
        {
            name: "toy ms marvel",
            category: "accessories",
            price: 12,
            description: "toy ms marvel for kids",
            image: `/img/2.png`,
            onSale: true,
            owner,
        },
        {
            name: "toy flash",
            category: "accessories",
            price: 8,
            description: "toy flash for kid",
            image: `/img/3.png`,
            onSale: true,
            owner,
        },
        {
            name: "clothes marvel",
            category: "clothes",
            price: 18,
            description: "article of clothing",
            image: `/img/4.png`,
            onSale: true,
            owner,
        },
        {
            name: "infinity gauntlet",
            category: "accessories",
            price: 10,
            description: "infinity gauntlet for kids",
            image: `/img/1.png`,
            onSale: true,
            owner,
        },
        {
            name: "toy ms marvel",
            category: "accessories",
            price: 12,
            description: "toy ms marvel for kids",
            image: `/img/2.png`,
            onSale: true,
            owner,
        },
        {
            name: "toy flash",
            category: "accessories",
            price: 8,
            description: "toy flash for kid",
            image: `/img/3.png`,
            onSale: true,
            owner,
        },
        {
            name: "clothes marvel",
            category: "clothes",
            price: 18,
            description: "article of clothing",
            image: `/img/4.png`,
            onSale: true,
            owner,
        },
        {
            name: "infinity gauntlet",
            category: "accessories",
            price: 10,
            description: "infinity gauntlet for kids",
            image: `/img/1.png`,
            onSale: true,
            owner,
        },
        {
            name: "toy ms marvel",
            category: "accessories",
            price: 12,
            description: "toy ms marvel for kids",
            image: `/img/2.png`,
            onSale: true,
            owner,
        },
        {
            name: "toy flash",
            category: "accessories",
            price: 8,
            description: "toy flash for kid",
            image: `/img/3.png`,
            onSale: true,
            owner,
        },
        {
            name: "clothes marvel",
            category: "clothes",
            price: 18,
            description: "article of clothing",
            image: `/img/4.png`,
            onSale: true,
            owner,
        },
        {
            name: "infinity gauntlet",
            category: "accessories",
            price: 10,
            description: "infinity gauntlet for kids",
            image: `/img/1.png`,
            onSale: true,
            owner,
        },
        {
            name: "toy ms marvel",
            category: "accessories",
            price: 12,
            description: "toy ms marvel for kids",
            image: `/img/2.png`,
            onSale: true,
            owner,
        },
        {
            name: "toy flash",
            category: "accessories",
            price: 8,
            description: "toy flash for kid",
            image: `/img/3.png`,
            onSale: true,
            owner,
        },
        {
            name: "clothes marvel",
            category: "clothes",
            price: 18,
            description: "article of clothing",
            image: `/img/4.png`,
            onSale: true,
            owner,
        },
        {
            name: "infinity gauntlet",
            category: "accessories",
            price: 10,
            description: "infinity gauntlet for kids",
            image: `/img/1.png`,
            onSale: true,
            owner,
        },
        {
            name: "toy ms marvel",
            category: "accessories",
            price: 12,
            description: "toy ms marvel for kids",
            image: `/img/2.png`,
            onSale: true,
            owner,
        },
        {
            name: "toy flash",
            category: "accessories",
            price: 8,
            description: "toy flash for kid",
            image: `/img/3.png`,
            onSale: true,
            owner,
        },
        {
            name: "clothes marvel",
            category: "clothes",
            price: 18,
            description: "article of clothing",
            image: `/img/4.png`,
            onSale: true,
            owner,
        },
    ];
};
export default productSeeds;
